// <auto-generated />
using IDO_server_side.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDO_server_side.Migrations
{
    [DbContext(typeof(IDODbContext))]
    [Migration("20240127210748_SeedInitialItems")]
    partial class SeedInitialItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IDO_server_side.Models.ApplicationUser", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            email = "ammarmalass@gmail.com",
                            password = "$2a$13$5lSI0CYJ1fXqOCX.zi3mRucHkvHvzPz8DK0Mxw5lNEBD5zsNts6gW"
                        },
                        new
                        {
                            userId = 2,
                            email = "ahmadali@gmail.com",
                            password = "$2a$13$nPl1ao4HDzQC0jYLVbZi.uMndoYV15N9bY5PSuIAUzi0wGtzcPG4u"
                        },
                        new
                        {
                            userId = 3,
                            email = "khaledtaha@gmail.com",
                            password = "$2a$13$beBLC.2xOmr9AArMNAVhlO7LuqbXzMsoqfIdaVG.tO45./DrzU8Py"
                        });
                });

            modelBuilder.Entity("IDO_server_side.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estimate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("importance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category = "Follow Up",
                            dueDate = "01/10/2022",
                            estimate = "0.5 hours",
                            importance = "medium",
                            name = "Contact the support team of XYZ software to ask about the guarantee pricing",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 2,
                            category = "Final Year Project",
                            dueDate = "None",
                            estimate = "15 minutes",
                            importance = "",
                            name = "Email the faculty director about the progress",
                            status = "done",
                            userId = 1
                        },
                        new
                        {
                            id = 3,
                            category = "House improvements",
                            dueDate = "None",
                            estimate = "1 hour",
                            importance = "medium",
                            name = "Fix the power button of the TV",
                            status = "doing",
                            userId = 1
                        },
                        new
                        {
                            id = 4,
                            category = "General cleanup",
                            dueDate = "12/10/2022",
                            estimate = "3 hours",
                            importance = "low",
                            name = "Format the PC",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 5,
                            category = "final year project",
                            dueDate = "01/01/2022",
                            estimate = "8 days",
                            importance = "hight",
                            name = "Prepare The XD Design",
                            status = "done",
                            userId = 1
                        },
                        new
                        {
                            id = 6,
                            category = "Job opportunity",
                            dueDate = "10/10/2022",
                            estimate = "2 hours",
                            importance = "low",
                            name = "Translate The Resume",
                            status = "doing",
                            userId = 1
                        },
                        new
                        {
                            id = 7,
                            category = "Job opportunity",
                            dueDate = "Sunday at midnight",
                            estimate = "5 days",
                            importance = "hight",
                            name = "Do OSD Assessment",
                            status = "doing",
                            userId = 1
                        },
                        new
                        {
                            id = 8,
                            category = "Education",
                            dueDate = "12/12/2022",
                            estimate = "6 hours",
                            importance = "hight",
                            name = "Prepare The Assay",
                            status = "toDo",
                            userId = 1
                        },
                        new
                        {
                            id = 9,
                            category = "Work",
                            dueDate = "02/28/2023",
                            estimate = "10 hours",
                            importance = "hight",
                            name = "Complete Project Proposal",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 10,
                            category = "Education",
                            dueDate = "03/15/2023",
                            estimate = "2 hours",
                            importance = "medium",
                            name = "Read Chapter 5 for Exam",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 11,
                            category = "Personal",
                            dueDate = "Tomorrow",
                            estimate = "5 hours",
                            importance = "hight",
                            name = "Plan Weekend Trip",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 12,
                            category = "Career",
                            dueDate = "None",
                            estimate = "3 hours",
                            importance = "medium",
                            name = "Update Resume",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 13,
                            category = "Health",
                            dueDate = "02/20/2023",
                            estimate = "1 hour",
                            importance = "medium",
                            name = "Exercise Session",
                            status = "toDo",
                            userId = 2
                        },
                        new
                        {
                            id = 14,
                            category = "Personal Development",
                            dueDate = "03/10/2023",
                            estimate = "4 hours",
                            importance = "hight",
                            name = "Research New Technologies",
                            status = "doing",
                            userId = 3
                        },
                        new
                        {
                            id = 15,
                            category = "Errands",
                            dueDate = "None",
                            estimate = "1.5 hours",
                            importance = "low",
                            name = "Grocery Shopping",
                            status = "done",
                            userId = 3
                        },
                        new
                        {
                            id = 16,
                            category = "Hobby",
                            dueDate = "03/05/2023",
                            estimate = "3 hours",
                            importance = "medium",
                            name = "Write Blog Post",
                            status = "done",
                            userId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
